id: P046A0535
initial_creation_type: input
source_metadata:
  Title: Vijnaptimatratasiddhi prakarana dvayam
  Editor: Tripathi, Ram Shankar
  Publisher: Sampurnananda Sanskrit University
  Place of Publication: Varanasi
  Year: '1992'
  Viṃśatikākārikā:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Milan Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:57:16.585790'
last_modified_at: '2022-03-08T16:57:16.585799'
